apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: flask_app
spec:
  type: NodePort
  selector:
    app: flask_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000